name: webdav_client
description: A simple WebDAV client that supports some common methods.

version: 1.2.2
homepage: https://github.com/flymzero/webdav_client

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.8.0
  xml: ^6.5.0
  convert: ^3.1.2

dev_dependencies:
  test: ^1.0.0
