import 'dart:convert';

import 'package:webdav_client_plus/src/internal/hash_utils.dart';

/// Auth for WebDAV client
sealed class Auth {
  const Auth();

  /// Get authorization data
  String? authorize(String method, String path) => null;
}

/// NoAuth - No authentication
class NoAuth extends Auth {
  const NoAuth();

  @override
  String? authorize(String method, String path) => null;
}

/// BasicAuth
///
/// eg.:
/// ```dart
/// final auth = BasicAuth(user: 'user', pwd: 'pwd');
/// ```
final class BasicAuth extends Auth {
  /// Username for Basic Authentication
  final String user;

  /// Password for Basic Authentication
  final String pwd;

  /// Constructor for [BasicAuth] with username and password
  const BasicAuth({
    required this.user,
    required this.pwd,
  });

  @override
  String authorize(String method, String path) {
    final List<int> bytes = utf8.encode('$user:$pwd');
    return 'Basic ${base64Encode(bytes)}';
  }
}

/// BearerAuth
///
/// eg. `Bearer token`
final class BearerAuth extends Auth {
  /// Token for Bearer Authentication
  final String token;

  /// Constructor for [BearerAuth] with token
  /// The token is typically a JWT (JSON Web Token) or similar
  /// used for authentication in APIs.
  const BearerAuth({
    required this.token,
  });

  @override
  String authorize(String method, String path) {
    return 'Bearer $token';
  }
}

/// DigestAuth
///
/// It's a more secure way to authenticate than BasicAuth.
final class DigestAuth extends Auth {
  /// Username for Digest Authentication
  final String user;

  /// Password for Digest Authentication
  final String pwd;

  /// [DigestParts] object containing the parsed parameters from the server
  /// used for digest calculation.
  /// This includes nonce, realm, qop, opaque, algorithm, entityBody, and charset.
  /// These parameters are extracted from the server's WWW-Authenticate header
  /// and are essential for generating the correct digest response.
  final DigestParts digestParts;

  // Track nonce count for proper digest implementation
  int _nonceCount = 0;

  /// Constructor for [DigestAuth] with username, password, and digest parts
  DigestAuth({
    required this.user,
    required this.pwd,
    required this.digestParts,
  });

  /// {@template digest_auth_parts}
  /// The parameters used in Digest Authentication
  /// - `nonce`: A unique string generated by the server for this authentication attempt.
  /// - `realm`: A string that defines the protection space.
  /// - `qop`: Quality of protection (auth, auth-int).
  /// - `opaque`: A server-provided string that should be returned unchanged.
  /// - `algorithm`: The hash algorithm to use (MD5, SHA-256, etc.).
  /// - `entityBody`: Used for auth-int qop.
  /// - `charset`: Character encoding for the credentials.
  /// {@endtemplate}
  String? get nonce => digestParts.parts['nonce'];

  /// {@macro digest_auth_parts}
  String? get realm => digestParts.parts['realm'];

  /// {@macro digest_auth_parts}
  String? get qop => digestParts.parts['qop'];

  /// {@macro digest_auth_parts}
  String? get opaque => digestParts.parts['opaque'];

  /// {@macro digest_auth_parts}
  String? get algorithm => digestParts.parts['algorithm'];

  /// {@macro digest_auth_parts}
  String? get entityBody => digestParts.parts['entityBody'];

  /// {@macro digest_auth_parts}
  String? get charset => digestParts.parts['charset'];

  /// Whether the server requested RFC 7616 username hashing.
  String? get userhash => digestParts.parts['userhash'];

  @override
  String authorize(String method, String path) {
    digestParts.uri = path;
    digestParts.method = method;
    return _getDigestAuthorization();
  }

  String _getDigestAuthorization() {
    // Increment nonce count with each request using the same nonce
    _nonceCount++;

    // Format nonce count as 8 digit hex
    final nc = _nonceCount.toRadixString(16).padLeft(8, '0');

    final cnonce = computeNonce();
    final ha1 = _computeHA1(cnonce);
    final ha2 = _computeHA2();
    final response = _computeResponse(ha1, ha2, nc, cnonce);

    // Build authorization header according to RFC
    final authHeader = StringBuffer('Digest');
    final useUserhash = userhash?.toLowerCase() == 'true';
    final usernameValue = useUserhash ? _hashByAlgorithm('$user:$realm') : user;
    _addParam(authHeader, 'username', usernameValue);
    if (useUserhash) {
      _addParam(authHeader, 'userhash', 'true', quote: false);
    }
    _addParam(authHeader, 'realm', realm);
    _addParam(authHeader, 'nonce', nonce);
    _addParam(authHeader, 'uri', digestParts.uri);
    _addParam(authHeader, 'response', response);

    if (algorithm?.isNotEmpty == true) {
      _addParam(authHeader, 'algorithm', algorithm, quote: false);
    }

    final selectedQop = _selectedQop;
    if (selectedQop != null && selectedQop.isNotEmpty) {
      _addParam(authHeader, 'qop', selectedQop, quote: false);
      _addParam(authHeader, 'nc', nc, quote: false);
      _addParam(authHeader, 'cnonce', cnonce);
    }

    if (opaque?.isNotEmpty == true) {
      _addParam(authHeader, 'opaque', opaque);
    }

    if (charset?.isNotEmpty == true) {
      _addParam(authHeader, 'charset', charset, quote: false);
    }

    return authHeader.toString().trim();
  }

  // Helper to add parameter to the authorization header
  void _addParam(
    StringBuffer sb,
    String name,
    String? value, {
    bool quote = true,
  }) {
    if (value == null || value.isEmpty) return;

    if (sb.length > 7) {
      // "Digest " is 7 chars
      sb.write(', ');
    } else {
      sb.write(' ');
    }

    sb.write('$name=');
    if (quote) sb.write('"');
    sb.write(quote ? _escapeQuotedString(value) : value);
    if (quote) sb.write('"');
  }

  String _escapeQuotedString(String value) {
    return value.replaceAll(r'\', r'\\').replaceAll('"', r'\"');
  }

  String _computeHA1(String cnonce) {
    final alg = algorithm?.toLowerCase();
    final base = _hashByAlgorithm('$user:$realm:$pwd');

    if (alg != null && alg.endsWith('-sess')) {
      return _hashByAlgorithm('$base:$nonce:$cnonce');
    }

    return base;
  }

  String _computeHA2() {
    final selectedQop = _selectedQop;

    if (selectedQop == null || selectedQop.isEmpty || selectedQop == 'auth') {
      return _hashByAlgorithm('${digestParts.method}:${digestParts.uri}');
    }
    // selectedQop == 'auth-int'
    final bodyHash = _hashByAlgorithm(entityBody ?? '');
    return _hashByAlgorithm(
        '${digestParts.method}:${digestParts.uri}:$bodyHash');
  }

  String _computeResponse(String ha1, String ha2, String nc, String cnonce) {
    final selectedQop = _selectedQop;

    if (selectedQop == null || selectedQop.isEmpty) {
      return _hashByAlgorithm('$ha1:$nonce:$ha2');
    } else {
      return _hashByAlgorithm('$ha1:$nonce:$nc:$cnonce:$selectedQop:$ha2');
    }
  }

  /// Select a single qop token from the server's comma-separated challenge.
  ///
  /// RFC 7616 sends qop-options as a quoted list (for example
  /// `qop="auth,auth-int"`), while the Authorization header and response hash
  /// must contain exactly one chosen token. Prefer `auth` for interoperability,
  /// falling back to `auth-int` or the first extension token.
  String? get _selectedQop {
    final value = qop;
    if (value == null || value.trim().isEmpty) {
      return null;
    }

    final tokens = value
        .split(',')
        .map((token) => token.trim().toLowerCase())
        .where((token) => token.isNotEmpty)
        .toList(growable: false);
    if (tokens.isEmpty) {
      return null;
    }
    if (tokens.contains('auth')) {
      return 'auth';
    }
    if (tokens.contains('auth-int')) {
      return 'auth-int';
    }
    return null;
  }

  String _hashByAlgorithm(String data) {
    var alg = algorithm?.toLowerCase();
    if (alg != null && alg.endsWith('-sess')) {
      alg = alg.substring(0, alg.length - '-sess'.length);
    }

    if (alg != null) {
      if (alg == 'sha-512-256' || alg == 'sha512-256') {
        return sha512256Hash(data);
      } else if (alg == 'sha-512' || alg == 'sha512') {
        return sha512Hash(data);
      } else if (alg == 'sha-256' || alg == 'sha256') {
        return sha256Hash(data);
      }
    }

    // Default to MD5 if no algorithm is specified or recognized
    return md5Hash(data);
  }
}

/// DigestParts
///
/// Class for parsing and storing HTTP Digest Authentication parameters
/// as defined in RFC 2617 and RFC 7616
class DigestParts {
  /// Constructor that parses WWW-Authenticate header from server
  ///
  /// @param authHeader The WWW-Authenticate header value from server response
  DigestParts(String? authHeader) {
    if (authHeader != null) {
      // First, extract the authentication scheme
      var headerData = authHeader;
      if (authHeader.toLowerCase().startsWith('digest')) {
        // Remove 'Digest ' prefix to isolate the parameters
        headerData = authHeader.substring(6).trim();
      }

      // Parse the header values according to RFC specification
      _parseAuthHeader(headerData);
    }
  }

  /// Request URI for digest calculation
  String uri = '';

  /// HTTP method for digest calculation (GET, PUT, etc.)
  String method = '';

  /// Storage for all digest authentication parameters
  ///
  /// Common parameters include:
  /// - nonce: Server-generated unique string for this authentication attempt
  /// - realm: String that defines the protection space
  /// - qop: Quality of protection (auth, auth-int)
  /// - opaque: Server-provided string that should be returned unchanged
  /// - algorithm: Hash algorithm to use (MD5, SHA-256, etc.)
  /// - entityBody: Used for auth-int qop
  /// - charset: Character encoding for the credentials
  Map<String, String> parts = {
    'nonce': '',
    'realm': '',
    'qop': '',
    'opaque': '',
    'algorithm': '',
    'entityBody': '',
    'charset': '',
    'userhash': '',
  };

  /// Parses the authentication header into key-value pairs.
  ///
  /// Extracts all parameters from the WWW-Authenticate header and stores them
  /// for later digest calculation. This parser follows RFC 7616 quoted-string
  /// handling so commas and escaped characters inside quoted values are
  /// preserved instead of being treated as parameter separators.
  void _parseAuthHeader(String headerData) {
    var index = 0;

    void skipWhitespaceAndCommas() {
      while (index < headerData.length) {
        final char = headerData[index];
        if (char == ',' || char.trim().isEmpty) {
          index++;
        } else {
          break;
        }
      }
    }

    while (index < headerData.length) {
      skipWhitespaceAndCommas();
      if (index >= headerData.length) {
        break;
      }

      final keyStart = index;
      while (index < headerData.length && headerData[index] != '=') {
        index++;
      }
      if (index >= headerData.length) {
        break;
      }

      final key = headerData.substring(keyStart, index).trim().toLowerCase();
      index++; // Skip '='.
      while (index < headerData.length && headerData[index].trim().isEmpty) {
        index++;
      }

      String value;
      if (index < headerData.length && headerData[index] == '"') {
        index++; // Skip opening quote.
        final buffer = StringBuffer();
        var escaping = false;
        while (index < headerData.length) {
          final char = headerData[index++];
          if (escaping) {
            buffer.write(char);
            escaping = false;
          } else if (char == r'\') {
            escaping = true;
          } else if (char == '"') {
            break;
          } else {
            buffer.write(char);
          }
        }
        value = buffer.toString();
      } else {
        final valueStart = index;
        while (index < headerData.length && headerData[index] != ',') {
          index++;
        }
        value = headerData.substring(valueStart, index).trim();
      }

      if (key.isNotEmpty) {
        parts[key] = value;
      }
    }
  }

  /// Creates a string representation of the digest parts
  @override
  String toString() {
    return 'DigestParts{uri: $uri, method: $method, parts: $parts}';
  }
}
